### ISSUE TITLE
pruebas de funcionalidad en el mid

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_mid#12]
se requiere realizar pruebas de funcionalidad a nivel de las funciones que realiza el mid, dichas funciones probadas en ambiente de test

**Comment by BrayanB24** [comment]
Se realizan pruebas de funcionalidad del MID en cuanto a replica de datos y servicio que provee información a Argo, corroborando que todo funciona como debería. Por tanto se queda a la espera de que el lider técnico @BOTOOM apruebe este procedimiento.

**Comment by BOTOOM** [comment]
el issue y las tareas asignadas en el mismo son aprobadas
