### ISSUE TITLE
creación de función en el mid de novedades para replica de datos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_mid#2]
(descripción actualizada ya que no se ha de usar mas el api NoSql pra las novedades).

***nota importante: esta duplicidad solo se realiza para las novedades de adición y cesión***

En seguida del issue #3  se requiere crear una función que permita hacer la duplicidad del ID 

- [x] Definir el nombre del Endpoint. 

- [x] Debe enviar los Datos que recibe del cliente y mandarlos al Crud de novedades.

- [x] Duplicar el ID y datos de la novedad y enviarlos a las respectivas apis como se describirá a continuación:
   - [x] enviar los datos de la novedad por medio del api [administrativa_amazon_api
](https://github.com/udistrital/administrativa_amazon_api) al endpoint de `novedad_postcontractual`
   - [x] el ID de la novedad ingresada en novedades crud y en administrativa_amazon , deben ser almacenados ambos ids en el almacén de datos por medio de un servicio de jbpm

- [x] respuesta enviada al cliente debe ser en formato JSON.

**Comment by BrayanB24** [comment]
Como primera etapa de desarrollo se requiere que se diseñe un controlador el cual pueda recibir la peticion POST que realiza el cliente con los datos de las novedades a registrar y este devuleva un JSON con lo enviado. Esta prueba se realiza de manera inicial para corregir las respuestas del controlador y dejar punto de partida para realizar lass peticiones a los CRUD correspondientes.

**Comment by BrayanB24** [comment]
Realizada la prueba y observando los resultados exitosos, el siguiente paso es definir cuales son los datos que se deben duplicar en la base SQL. Para esto el equipo se reune y analizando la DB Mongo se definirán estos datos y los endpoint de las API CRUD correspondientes que realizarán el registro en la DB SQL, para así dar continuidad al desarrollo del controlador de la función.

**Comment by BrayanB24** [comment]
Luego de la reunión con el equipo de soporte se decide que los datos necesarios a guardar en un modelo de base de datos relacional, corresponde con la siguiente descripción de tipo estructura:

`type Novedad struct {
	Id                         bson.ObjectId `json:"_id" bson:"_id,omitempty"`
	Aclaracion                 string        `json:"aclaracion" bson:"aclaracion,omitempty"`
	Cedente                    int           `json:"cedente" bson:"cedente,omitempty"`
	Cesionario                 int           `json:"cesionario" bson:"cesionario,omitempty"`
	Contrato                   string        `json:"contrato" bson:"contrato,omitempty"`
	FechaAdicion               time.Time     `json:"fechaadicion" bson:"fechaadicion,omitempty"`
	FechaCesion                time.Time     `json:"fechacesion" bson:"fechacesion,omitempty"`
	FechaLiquidacion           time.Time     `json:"fechaliquidacion" bson:"fechaliquidacion,omitempty"`
	FechaProrroga              time.Time     `json:"fechaprorroga" bson:"fechaprorroga,omitempty"`
	FechaRegistro              time.Time     `json:"fecharegistro"`
	FechaReinicio              time.Time     `json:"fechareinicio" bson:"fechareinicio,omitempty"`
	FechaSolicitud             time.Time     `json:"fechasolicitud"`
	FechaSuspension            time.Time     `json:"fechasuspension" bson:"fechasuspension,omitempty"`
	FechaTerminacionAnticipada time.Time     `json:"fechaterminacionanticipada" bson:"fechaterminacionanticipada,omitempty"`
	Motivo                     string        `json:"motivo"`
	//NumeroActaEntrega          int           `json:"numeroactaentrega" bson:"numeroactaentrega,omitempty"`
	NumeroCDP                  string        `json:"numerocdp" bson:"numerocdp,omitempty"`
	NumeroSolicitud            int           `json:"numerosolicitud"`
	Observacion                string        `json:"observacion"`
	PeriodoSuspension          int           `json:"periodosuspension" bson:"periodosuspension,omitempty"`
	PlazoActual                int           `json:"plazoactual" bson:"plazoactual,omitempty"`
	Poliza                     string        `json:"poliza" bson:"poliza,omitempty"`
    EntidadPoliza              string        `json:"entidad" bson:"entidad,omitempty"`
	TiempoProrroga             int           `json:"tiempoprorroga" bson:"tiempoprorroga,omitempty"`
	Tiponovedad                string        `json:"tiponovedad"`
	ValorAdicion               int           `json:"valoradicion" bson:"valoradicion,omitempty"`
    ValorContratoCesionado     int           `json:"valorcontratocesionado" bson:"valorcontratocesionado,omitempty"`
	ValorFinalContrato         int           `json:"valorfinalcontrato" bson:"valorfinalcontrato,omitempty"`
	Vigencia                   string        `json:"vigencia"`
}`

Se esperará modelo de base de datos relacional a implementar.

**Comment by BrayanB24** [comment]
El modelo de Acta de inicio: 

```
type Actainicio struct {
	Id          bson.ObjectId `json:"_id" bson:"_id,omitempty"`
	Contrato    string        `json:"contrato"`
	Vigencia    string        `json:"vigencia"`
	FechaInicio time.Time     `json:"fechainicio"`
	FechaFin    time.Time     `json:"fechafin"`
}
```

**Comment by BrayanB24** [comment]
El modelo de tipo de novedad:

```
type Tiponovedad struct {
	Id          bson.ObjectId `json:"_id" bson:"_id,omitempty"`
	Nombre      string        `json:"nombre"`
	Descripcion string        `json:"descripcion"`
}
```

**Comment by BOTOOM** [comment]
guardado en mongo:

```go
   type Novedad struct {
	Id                         bson.ObjectId `json:"_id" bson:"_id,omitempty"`
	Aclaracion                 string        `json:"aclaracion" bson:"aclaracion,omitempty"`
	Contrato                   string        `json:"contrato" bson:"contrato,omitempty"`
	FechaAdicion               time.Time     `json:"fechaadicion" bson:"fechaadicion,omitempty"`
	FechaCesion                time.Time     `json:"fechacesion" bson:"fechacesion,omitempty"`
	FechaLiquidacion           time.Time     `json:"fechaliquidacion" bson:"fechaliquidacion,omitempty"`
	FechaProrroga              time.Time     `json:"fechaprorroga" bson:"fechaprorroga,omitempty"`
	FechaRegistro              time.Time     `json:"fecharegistro"`
	FechaReinicio              time.Time     `json:"fechareinicio" bson:"fechareinicio,omitempty"`
	FechaSolicitud             time.Time     `json:"fechasolicitud"`
	FechaSuspension            time.Time     `json:"fechasuspension" bson:"fechasuspension,omitempty"`
	FechaTerminacionAnticipada time.Time     `json:"fechaterminacionanticipada" bson: "fechaterminacionanticipada,omitempty"`
	Motivo                     string        `json:"motivo"`
	NumeroCDP                  string        `json:"numerocdp" bson:"numerocdp,omitempty"`
	NumeroSolicitud            int           `json:"numerosolicitud"`
	Observacion                string        `json:"observacion"`
	PeriodoSuspension          int           `json:"periodosuspension" bson:"periodosuspension,omitempty"`
	PlazoActual                int           `json:"plazoactual" bson:"plazoactual,omitempty"`
	Poliza                     string        `json:"poliza" bson:"poliza,omitempty"`
	TiempoProrroga             int           `json:"tiempoprorroga" bson:"tiempoprorroga,omitempty"`
	Tiponovedad                string        `json:"tiponovedad"`
	ValorAdicion               int           `json:"valoradicion" bson:"valoradicion,omitempty"`
	Vigencia                   string        `json:"vigencia"`
   }
```

**Comment by BOTOOM** [comment]
datos guardados en administrativa_amazon ... novedadpostcontractual

```
numero_contrato, vigencia,
tipo_novedad,
fecha_registro,
numero_cdp,
vigencia_cdp,
plazo_ejecucion,
unidad_ejecucion,
valor_novedad,
fecha_inicio_poliza,
fecha_fin_poliza,
numero_poliza,
entidad_aseguradora,
fecha_aprobacion,
fecha_expedicion
```

**Comment by BrayanB24** [comment]
Se guarda de manera correcta los datos enviados desde el cliente hacia el MID. Para cotinuar con la réplica de los datos es necesario resolver el conflicto de los ID Hexadecimal que se explica acontinuación:

Actualmente se utiliza la librería mgo para conexión con la base de datos de Mongo, en principio al realizar el proceso de insertar datos con la función ```c.insert()```  solo se devuelve una bandera que indica si el proceso de guardado en la base se realizó de manera correcta o no, pero este no devuelve ningún tipo de dato relacionado con lo que se acaba de guardar (como el ID). Al no ser envíado el ID desde la petición, mongo la genera automaticamente en la base y este es guardado, al no ser retornado por la función este ID "se pierde" en la operación. Se pueden plantear soluciones a nivel de programación como una re consulta a la base para buscar el último registro guardado pero esto no sería una solución estable para la API. Hablando con desarrolladores indican que la manera correcta es generar el ID antes de guardar en la base para que se tenga la trazabilidad de este mismo. Existe la función que genera el ID la cual se llama ```bson.NewObjectId()``` pero este no se asegura que ese ID generado no exista ya en la base de datos, por lo que el proceso a seguir es generar una transcción sobre el guardado de datos en mongo para que se asegure que el ID generado es único en la base de datos y no tener problemas de guardado y poder retornar el ID.

Se queda a la espera de una desición por parte del lider técnico del proyecto @BOTOOM .

**Comment by BOTOOM** [comment]
leyendo el presente caso lo recomendable para mongo es optar por la ultima opción mencionada en la cual se genere el ID en el api, para verificar si el ID no esta repetido se puede hacer una consulta por ese ID y saber si ya existe un registro o no. Adicionalmente hablando con el desarrollador @BrayanB24 menciona que si el ID ya existe , la inserción es rechazada, por lo tanto se puede realizar el generar un ID, luego realizar la inserción y si falla generar uno nuevo y repetir el proceso.

la cuestión con esto es que el modelo de mongo no se va a mantener por mucho tiempo por lo tanto, se recomienda solo tener el ID durante estas pruebas, y replicar los datos a donde es necesario, ya que se ha de implementar en un futuro cercano Api para un modelo de datos relacional , siendo esta Api para postgres la cual tendrá un mejor manejo de error a comparación del Api para el modelo de mongo. por lo tanto el problema que se tiene actualmente , el cual se menciona en el comentari anterior, sera solucionado al implementar la nueva Api

**Comment by BrayanB24** [comment]
Se retoma el desarrollo con la nueva API desarrollada en Posgresql, se especifíca que el ID ya se devuelve de manera correcta y puede ser almacenado en la tabla necesaria. Por otro lado, el servicio de JBPM ya fue solicitado y fue implementado, por lo que se comienza primero a llenar las tablas paramétricas del CRUD de novedades para comenzar a desarrollar la función de la duplicidad de los datos.

**Comment by BrayanB24** [comment]
Terminada la restauración de las tablas paramétricas del CRUD, se pasa al desarrollo de la funcionalidad de duplicidad de datos.

**Comment by BrayanB24** [comment]
Se deben aclarar algunos de los campos que se guardan en Administrativa_amazon_api. Como por ejemplo el campo de UnidadEjecucion, PlazoEjecucion y ValorNovedad. Por un lado se preguntó sobre la UnidadEjecución y se especifica que existen dos grandes rubros en la universidad, Rectoría y IDEXUD, por lo que la novedad poscontractual va ligada al rubro al que está ligado el contratista y de esta manera se sabrá cual número corresponde a ese valor de UnidadEjecucion. Se debe establecer el mecanismo para conocer cual es el rubro de donde hace parte el contratista, tanto para la novedad de adición como para la de cesión. @BOTOOM

**Comment by BrayanB24** [comment]
para la correspondencia de los ID de las novedades poscontractuales es lo siguiente: 

- ID 219 corresponde a la novedad de Cesión

- ID 220 corresponde a la novedad de Adición

**Comment by BrayanB24** [comment]
Hablando con la persona encargada de las novedades poscontractuales se indica que "UnidadEjecucion" hace referencia a la unidad en la que se ejecuta la novedad (días, meses y años). El "PlazoEjecucion" hace referencia al número ya sea en días meses o años que va a tomar la novedad. y por último "ValorNovedad" solo se utiliza en las novedades de adición y hace referencia al valor adicionado en la novedad. Estos datos pueden ser obtenidos de la tabla argo.parametros .

**Comment by BrayanB24** [comment]
Se habla de que actualmente las fechas de inicio y fin se están escribiendo desde condor. Se está a la espera de que la persona que las registra actualmente, especifique si se van a seguir manejando desde condor y de que forma, por lo que, es necesario tener claro este paso para poder registrar la novedad.

**Comment by BrayanB24** [comment]
También mediante Kanban registrado a el DBA se solicitan permisos del usuario de administrativa_amazon_api sobre la tabla respectiva de novedades poscontractuales para poder realizar el registro de la novedad, porque a día de hoy luego del cambio de contraseñas por seguridad de las DB no hay permisos para tal fin. Se está a la espera de que sean otorgados los permisos.
