### ISSUE TITLE
Desarrollo en API MID para creación o ajuste de endpoints

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_mid#35]
Se debe realizar el desarrollo necesario en novedades_mid y las tareas que esto requiera (Creación o ajuste de controladores, helpers, modelos, rutas), de forma que se pueda acceder, controlar y utilizar la información relacionada con el módulo de novedades .

**Criterio de aceptación**

- [x] Creación de rama Feature de desarrollo en novedades_mid.

**Nota**: Tener en cuenta los lineamientos dispuestos por la OAS para la creación y carga de nuevas ramas en git.

**Comment by ricardoavendano** [comment]
Mid: Se crea función para guardar documentos en nuxeo con la implementación del gestor_documental_mid
udistrital/novedades_mid#38
