### ISSUE TITLE
cablear el api mid a la nueva api crud

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_mid#4]
al aprobarse el modelo de datos sql, se procederá a construir un api crud para este modelo el cual sera el remplazo del apli que gestiona mongo, por ende es necesario cablear y apuntar a esta nueva api

---

(edición el comentario del issue a continuación)
actualmente el modelo ha sido aprobado y el api esta finalizando su construcción.

por ende se requiere el poder conectarse a este y realizar las debidas transacciones y ajustes con esta.

para ello adicionalmente se contempla que lo realizado en el issue #2 estaba principalmente para la base de datos de mongo

en ese caso en este issue también se contempla la edición de ese método para ingresar.

***(nota:)  de ha visto el cogido y se puede reutilizar así que no es necesario realizarlo todo desde cero***

los items de check de colocaran al resolver una dudas con el desarrollador encargado

**Comment by BrayanB24** [comment]
Se termina con el desarrollo de la traducción de los JSON que envía el cliente para el nuevo api_crud en posgresql, queda pendiente revisar la novedad de suspensión para conocer exactamente cual es el PUT que realiza sobre la tabla. Se procede a realizar la traducción de todas las peticiones GET.

**Comment by BrayanB24** [comment]
La tarea se termina correctamente, se realizabn pruebas tanto de GET como de POST sobre todas las novedades poscontractuales, se queda a la espera de la revisión de pruebas desde el cliente por parte del desarrollador del mismo @anlramirezs11 .
