### ISSUE TITLE
endpoint y función para brindar datos a Argo(sara)

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_mid#6]
con el fin de proveerle información de la novedades almacenadas al servicio de argo(en sara) , se aclara que la información principalmente interesada para ellos es la información que ha sido replicada tales como las novedades de adición y cesión.

para esta función el endpint debe recibir un di, este id sera el di que ellos tienen almacenado en la base de datos que maneja el api de administrativa amazon. con este id se buscara en la tabla del almacén de datos, en dicha tabla esta el id de la novedad asociada que referenciara a la novedad de novedades_crud. se deberá de buscar la información sobre dicha novedad y devolverla como respuesta

**Comment by BrayanB24** [comment]
Se inicia desarrollo

**Comment by BrayanB24** [comment]
Para completar el servicio que le proporciona la replica de los datos a SARA es necesario que el servicio de JBPM tenga un getbyid (getone), por lo que el mismo ya fue solicitado y se está a la espera de que sea implementado.

**Comment by BrayanB24** [comment]
Se termina el desarrollo y se queda a la espera de las pruebas.
